# Generated by Django 5.1.4 on 2025-02-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixhelpers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
